import type {
  Expedition,
  Dataset,
  Publication,
  MediaItem,
  Activity,
  StationWeather,
  Region,
  Vessel,
} from "./types";

export const expeditions: Expedition[] = [
  {
    slug: "46th-isea",
    name: "46th Indian Scientific Expedition to Antarctica",
    designation: "46th ISEA",
    region: "Antarctica",
    station: "Maitri & Bharati",
    year: 2026,
    startDate: "2026-10",
    endDate: "2027-04",
    leader: "",
    status: "planned",
    crewCount: 80,
    ship: "Chartered ice-strengthened vessel",
    summary:
      "India's 46th Antarctic expedition is slated to depart in late 2026 to continue year-round operations at Maitri and Bharati stations, carrying winter-over teams, annual resupply and new cryosphere experiments.",
    objectives: [
      "Winter-over and summer scientific operations at Maitri and Bharati",
      "Annual cargo, fuel and food resupply for both stations",
      "Continuation of long-term ozone, radiation and AWS monitoring",
    ],
    highlights: [
      "Planned batch departures from Mumbai via Cape Town, October–November 2026",
    ],
    theme: "linear-gradient(135deg,#0c4a6e,#075985)",
    recent: true,
  },
  {
    slug: "45th-isea",
    name: "45th Indian Scientific Expedition to Antarctica",
    designation: "45th ISEA",
    region: "Antarctica",
    station: "Maitri & Bharati",
    year: 2025,
    startDate: "2025-10-31",
    endDate: "2026-05",
    leader: "",
    status: "active",
    crewCount: 100,
    ship: "M.V. Vasiliy Golovnin",
    summary:
      "The 45th ISEA is underway. The first team departed Mumbai on 31 October 2025 and reached Maitri on 4 November 2025, continuing India's uninterrupted scientific presence in Antarctica.",
    objectives: [
      "Winter-over maintenance of Maitri and Bharati stations",
      "Atmospheric, glaciological and biological research programmes",
      "Long-term meteorological and cryosphere monitoring",
    ],
    highlights: [
      "First batch departed Mumbai 31 October 2025 and reached Maitri 4 November 2025",
      "Seamless handover of the preceding winter-over team at Maitri",
    ],
    theme: "linear-gradient(135deg,#155e75,#0e7490)",
    recent: true,
  },
  {
    slug: "44th-isea",
    name: "44th Indian Scientific Expedition to Antarctica",
    designation: "44th ISEA",
    region: "Antarctica",
    station: "Maitri & Bharati",
    year: 2024,
    startDate: "2024-11",
    endDate: "2025-05",
    leader: "",
    status: "completed",
    crewCount: 103,
    ship: "M.V. Vasiliy Golovnin",
    summary:
      "The 44th ISEA involved 103 participants from 18 organisations. It redeployed an ice-tethered mooring in Quilty Bay, deployed a deep-ocean glider into the Southern Ocean (February–April 2025, ~1,200 km of sampling) and mapped 400+ km of the Nivl Ice Shelf with a radar-equipped hovercraft under the SENS campaign.",
    objectives: [
      "Year-round operations and resupply of Maitri and Bharati stations",
      "Ice-tethered mooring redeployment in Quilty Bay",
      "Deep-ocean glider deployment in the Southern Ocean sector",
      "Nivl Ice Shelf survey with hovercraft-based ground-penetrating radar (SENS)",
      "Multidisciplinary science supporting STAPLES (India, Belgium, Japan) collaboration",
    ],
    highlights: [
      "Ocean glider sampled ~1,200 km of the Southern Ocean from Feb to Apr 2025",
      "SENS hovercraft campaign mapped 400+ km across the Nivl Ice Shelf",
      "103 participants from 18 organisations, including new experiment groups",
    ],
    theme: "linear-gradient(135deg,#1e3a8a,#1d4ed8)",
  },
  {
    slug: "43rd-isea",
    name: "43rd Indian Scientific Expedition to Antarctica",
    designation: "43rd ISEA",
    region: "Antarctica",
    station: "Maitri & Bharati",
    year: 2023,
    startDate: "2023-10",
    endDate: "2024-05",
    leader: "",
    status: "completed",
    crewCount: 100,
    ship: "M.V. Vasiliy Golovnin",
    summary:
      "The 43rd ISEA was launched in October–November 2023 to relieve the winter-over team and sustain scientific and logistics support to Maitri and Bharati stations.",
    objectives: [
      "Relief of the 2022–23 winter-over team",
      "Continued atmospheric and cryosphere monitoring",
      "Annual resupply of both Antarctic stations",
    ],
    highlights: [
      "Winter-over team relieved in two batches via Cape Town",
      "Research on ice cores and glacial geology progressed towards the International Partnerships in Ice Core Sciences goals",
    ],
    theme: "linear-gradient(135deg,#0369a1,#0284c7)",
  },
  {
    slug: "42nd-isea",
    name: "42nd Indian Scientific Expedition to Antarctica",
    designation: "42nd ISEA",
    region: "Antarctica",
    station: "Maitri & Bharati",
    year: 2022,
    startDate: "2022-10-22",
    endDate: "2023-05",
    leader: "",
    status: "completed",
    crewCount: 104,
    ship: "M.V. Vasiliy Golovnin",
    summary:
      "The 42nd ISEA departed on 22 October 2022 with 104 members — 37 scientists from 19 national organisations and 67 support staff from 8 organisations — to maintain station operations and scientific research through the 2022–23 season.",
    objectives: [
      "Winter-over relief and station maintenance",
      "Atmospheric, glaciological and ecological research",
      "Annual resupply and logistics for Maitri and Bharati",
    ],
    highlights: [
      "104 participants: 37 scientists (19 organisations) + 67 support staff (8 organisations)",
      "Departed Cape Town on 22 October 2022 onboard M.V. Vasiliy Golovnin",
    ],
    theme: "linear-gradient(135deg,#1e3a8a,#1d4ed8)",
  },
  {
    slug: "41st-isea",
    name: "41st Indian Scientific Expedition to Antarctica",
    designation: "41st ISEA",
    region: "Antarctica",
    station: "Maitri & Bharati",
    year: 2021,
    startDate: "2021-11",
    endDate: "2022-05",
    leader: "Dr. Shailendra Saini",
    status: "completed",
    crewCount: 48,
    ship: "M.V. Vasiliy Golovnin",
    summary:
      "The 41st ISEA launched in November 2021; the first batch of 23 scientists reached Maitri, while ~48 members wintered over. It included geological exploration of the Amery Ice Shelf and a 500 m ice-core drilling programme near Maitri.",
    objectives: [
      "Resume full expedition science after COVID disruption",
      "Ice-core and glacial geology studies in Dronning Maud Land",
      "Winter-over relief at Maitri and Bharati",
    ],
    highlights: [
      "First batch of 23 scientists reached Maitri via Cape Town",
      "500 m ice-core drilling programme near Maitri",
      "Geological exploration of the Amery Ice Shelf region",
    ],
    theme: "linear-gradient(135deg,#065f46,#047857)",
  },
  {
    slug: "40th-isea",
    name: "40th Indian Scientific Expedition to Antarctica",
    designation: "40th ISEA",
    region: "Antarctica",
    station: "Maitri & Bharati",
    year: 2021,
    startDate: "2021-01-06",
    endDate: "2021-05",
    leader: "Dr. Yogesh Ray",
    status: "completed",
    crewCount: 43,
    ship: "M.V. Vasiliy Golovnin",
    summary:
      "The 40th ISEA departed Goa on 6 January 2021 with an expedition of 43 members — reduced in size because of COVID-19 — led by Dr. Yogesh Ray, with Atul Kulkarni (Maitri) and Ravindra More (Bharati) leading the station teams.",
    objectives: [
      "COVID-constrained relief of winter-over crews",
      "Station hygiene and health-safety management at Maitri and Bharati",
      "Priority science and annual resupply",
    ],
    highlights: [
      "Departure from Goa on 6 January 2021 with a reduced team of 43",
      "Voyage, Maitri and Bharati leadership by Dr. Yogesh Ray, Atul Kulkarni and Ravindra More respectively",
    ],
    theme: "linear-gradient(135deg,#3730a3,#4338ca)",
  },
  {
    slug: "39th-isea",
    name: "39th Indian Scientific Expedition to Antarctica",
    designation: "39th ISEA",
    region: "Antarctica",
    station: "Maitri & Bharati",
    year: 2019,
    startDate: "2019-12",
    endDate: "2020-05",
    leader: "Deepak Gajbhiye",
    status: "completed",
    crewCount: 51,
    ship: "M.V. Vasiliy Golovnin",
    summary:
      "The 39th ISEA (2019–20) was led at Maitri by Deepak Gajbhiye, at Bharati by Debdip Chakraborty, and on the voyage by Dr. Shailendra Saini, sustaining year-round research and logistics across both Indian Antarctic stations.",
    objectives: [
      "Winter-over relief and station resupply",
      "Maitri and Bharati research programme continuity",
    ],
    highlights: [
      "Station leaders: Deepak Gajbhiye (Maitri), Debdip Chakraborty (Bharati), Dr. Shailendra Saini (Voyage)",
    ],
    theme: "linear-gradient(135deg,#334155,#475569)",
  },
  {
    slug: "37th-isea",
    name: "37th Indian Scientific Expedition to Antarctica",
    designation: "37th ISEA",
    region: "Antarctica",
    station: "Bharati",
    year: 2017,
    startDate: "2017-12",
    endDate: "2018-05",
    leader: "Dr. Shailesh Pednekar",
    status: "completed",
    crewCount: 49,
    ship: "M.V. Vasiliy Golovnin",
    summary:
      "The 37th ISEA (2017–18) was led by Dr. Shailesh Pednekar, with Bagati Sudarshan Patro as part of the Bharati team, advancing the Antarctic programme's earth-system and logistics objectives.",
    objectives: [
      "Sustained winter-over operations at Bharati",
      "Southern Ocean and cryosphere observations en route",
    ],
    highlights: [
      "Dr. Shailesh Pednekar led voyage and Bharati contingent (2017–18)",
    ],
    theme: "linear-gradient(135deg,#1e3a8a,#1d4ed8)",
  },
  {
    slug: "33rd-isea",
    name: "33rd Indian Scientific Expedition to Antarctica",
    designation: "33rd ISEA",
    region: "Antarctica",
    station: "Maitri & Bharati",
    year: 2013,
    startDate: "2013-11",
    endDate: "2014-05",
    leader: "",
    status: "completed",
    crewCount: 50,
    ship: "M.V. Ivan Papanin",
    summary:
      "The 33rd ISEA (2013–14) sustained operations at Maitri and Bharati following the commissioning of Bharati in March 2012, contributing to India's permanent Antarctic presence.",
    objectives: [
      "Operations at Maitri and the newly commissioned Bharati",
      "Multidisciplinary Antarctic science across the 2013–14 season",
    ],
    highlights: [
      "Early season following Bharati's commissioning (18 March 2012)",
    ],
    theme: "linear-gradient(135deg,#0c4a6e,#075985)",
  },
  {
    slug: "1st-isea",
    name: "1st Indian Scientific Expedition to Antarctica",
    designation: "1st ISEA",
    region: "Antarctica",
    station: "Dakshin Gangotri",
    year: 1981,
    startDate: "1981-12",
    endDate: "1982-03",
    leader: "Dr. S. Z. Qasim",
    status: "completed",
    crewCount: 21,
    ship: "M.V. Polar Circel",
    summary:
      "India's first Antarctic expedition, led by Dr. S. Z. Qasim, departed Bombay on 6 December 1981 and landed on the Antarctic continent on 9 January 1982, marking the beginning of the Indian Antarctic Programme.",
    objectives: [
      "First Indian landing on Antarctica (9 January 1982)",
      "Preliminary gazetteer, meteorological and geoscientific reconnaissance",
      "Laying the foundation for a permanent Indian Antarctic base",
    ],
    highlights: [
      "21 members onboard M.V. Polar Circel under Dr. S. Z. Qasim",
      "Led to the establishment of Dakshin Gangotri (1983) and Maitri (1989)",
    ],
    theme: "linear-gradient(135deg,#3730a3,#4338ca)",
  },
  {
    slug: "16th-iare",
    name: "16th Indian Arctic Expedition",
    designation: "16th IArE",
    region: "Arctic",
    station: "Himadri, Ny-Ålesund",
    year: 2025,
    startDate: "2025-06",
    endDate: "2025-07",
    leader: "",
    status: "completed",
    crewCount: 15,
    ship: "—",
    summary:
      "The 16th Indian Arctic Expedition continued year-round atmospheric, oceanic and glaciological observations from Himadri, India's research station at Ny-Ålesund, Svalbard, alongside 15 expeditions completed till date.",
    objectives: [
      "Year-round atmospheric and aerosol observations at Himadri",
      "Fjord biogeochemistry and black-carbon deposition studies",
      "Glacier dynamics and permafrost observations in Svalbard",
    ],
    highlights: [
      "15 Indian Arctic Expeditions completed as of February 2025",
      "300+ days of winter operations at Himadri since December 2023",
    ],
    theme: "linear-gradient(135deg,#155e75,#0e7490)",
  },
  {
    slug: "1st-iare",
    name: "1st Indian Arctic Expedition",
    designation: "1st IArE",
    region: "Arctic",
    station: "Himadri, Ny-Ålesund",
    year: 2007,
    startDate: "2007-06",
    endDate: "2007-07",
    leader: "",
    status: "completed",
    crewCount: 10,
    ship: "—",
    summary:
      "India's first Arctic expedition established the initial Himadri station campaign at Ny-Ålesund, Svalbard; the station was formally inaugurated in July 2008.",
    objectives: [
      "Establish India's presence in Svalbard",
      "Pioneer atmospheric and glacier studies in the Arctic",
    ],
    highlights: [
      "Himadri station inaugurated at Ny-Ålesund in July 2008",
      "India's first permanent Arctic research platform",
    ],
    theme: "linear-gradient(135deg,#155e75,#0e7490)",
  },
  {
    slug: "soe-2004-pilot",
    name: "Pilot Indian Southern Ocean Expedition",
    designation: "SOE Pilot (I-1)",
    region: "Southern Ocean",
    station: "ORV Sagar Kanya",
    year: 2004,
    startDate: "2004-01",
    endDate: "2004-03",
    leader: "",
    status: "completed",
    crewCount: 50,
    ship: "ORV Sagar Kanya",
    summary:
      "The Indian Southern Ocean Research Programme was initiated in 2004 when the pilot expedition took place onboard ORV Sagar Kanya, establishing the multi-disciplinary, multi-institutional research framework coordinated by NCAOR/NCPOR.",
    objectives: [
      "Baseline hydrodynamics and biogeochemistry studies",
      "Air–sea interaction and lower-atmosphere observations",
      "Plankton and higher marine biodiversity sampling",
      "Palaeoceanographic sediment coring",
    ],
    highlights: [
      "Flagship voyage that started the Indian Southern Ocean Research Programme",
      "Onboard ORV Sagar Kanya under the Ministry of Earth Sciences",
    ],
    theme: "linear-gradient(135deg,#0369a1,#0284c7)",
  },
  {
    slug: "soe-2025",
    name: "Indian Southern Ocean Expedition 2025",
    designation: "SOE-2025",
    region: "Southern Ocean",
    station: "ORV",
    year: 2025,
    startDate: "2025-02",
    endDate: "2025-04",
    leader: "",
    status: "completed",
    crewCount: 30,
    ship: "Research vessel",
    summary:
      "As part of the 44th ISEA programme, a deep-ocean glider was deployed in the Indian Ocean sector of the Southern Ocean (February–April 2025), profiling ~1,200 km of upper-ocean temperature and salinity for the STAPLES collaboration.",
    objectives: [
      "Autonomous glider profiling of the Southern Ocean sector",
      "Upper-ocean physics support for STAPLES (India, Belgium, Japan)",
    ],
    highlights: [
      "Glider travelled ~1,200 km across the Antarctic Zone",
      "Near-real-time upper-ocean observations shared with partners",
    ],
    theme: "linear-gradient(135deg,#0369a1,#0284c7)",
  },
];

export const datasetCategories = [
  { name: "Atmosphere", count: 165, icon: "🌍", desc: "Aerosols, air quality, temperature, wind" },
  { name: "Oceans", count: 133, icon: "🌊", desc: "Ocean optics, bathymetry, biogeochemistry" },
  { name: "Cryosphere", count: 112, icon: "🧊", desc: "Glaciers, ice cores, sea ice" },
  { name: "Paleoclimate", count: 99, icon: "🕰️", desc: "Ice core and ocean/lake records" },
  { name: "Human Dimensions", count: 91, icon: "🏛️", desc: "Infrastructure and logistics" },
  { name: "Land Surface", count: 83, icon: "⛰️", desc: "Soils, geomorphology, permafrost" },
  { name: "Biological Classification", count: 58, icon: "🐧", desc: "Animals, plants and fungi" },
  { name: "Biosphere", count: 37, icon: "🌿", desc: "Aquatic and terrestrial ecosystems" },
  { name: "Solid Earth", count: 39, icon: "🪨", desc: "Geochemistry, rocks, minerals" },
  { name: "Sun-Earth Interactions", count: 19, icon: "☀️", desc: "Ionosphere, solar activity" },
] as const;

export const datasets: Dataset[] = [
  {
    id: "d001",
    title: "Maitri AWS Meteorological Hourly Series",
    category: "Atmosphere",
    description:
      "Real-time hourly automatic weather station observations of temperature, wind, pressure and humidity at Maitri station, Antarctica, served live by the NPDC data portal.",
    station: "Maitri, Antarctica",
    year: 2026,
    format: "NetCDF / CSV",
    size: "3.2 GB",
    records: "Live + archive",
  },
  {
    id: "d002",
    title: "Bharati DCWIS Surface Data",
    category: "Atmosphere",
    description:
      "Surface meteorological data from Bharati station including daily extremes, snow accumulation and DCWIS (Digital Cryosphere & Weather Information System) observations.",
    station: "Bharati, Antarctica",
    year: 2026,
    format: "CSV",
    size: "180 MB",
    records: "Live + archive",
  },
  {
    id: "d003",
    title: "Himadri AWS Series & Black Carbon (Aethalometer)",
    category: "Atmosphere",
    description:
      "Observational datasets from Himadri, Ny-Ålesund: automatic weather station series and aethalometer black-carbon concentrations supporting Arctic aerosol studies.",
    station: "Himadri, Arctic",
    year: 2025,
    format: "CSV",
    size: "96 MB",
    records: "52,000+ rows",
  },
  {
    id: "d004",
    title: "Himansh AWS Snow & Climate Series",
    category: "Atmosphere",
    description:
      "Automatic weather station time series from the Himalayan station Himansh (Chandra Basin, 4,080 m) including snow depth, radiation and temperature.",
    station: "Himansh, Himalaya",
    year: 2025,
    format: "CSV",
    size: "96 MB",
    records: "87,600 rows",
  },
  {
    id: "d005",
    title: "East Antarctic Ice Core Trace Metals",
    category: "Cryosphere",
    description:
      "Trace metal concentrations measured along ice cores recovered from Dronning Maud Land, East Antarctica, including the 500 m ice-core drilling programme near Maitri.",
    station: "Dronning Maud Land",
    year: 2024,
    format: "Excel / CSV",
    size: "24 MB",
    records: "18,000 obs",
  },
  {
    id: "d006",
    title: "Ocean Glider Upper-Ocean Profiles (SOE 2025)",
    category: "Oceans",
    description:
      "Temperature and salinity profiles collected by the deep-ocean glider deployed in the Indian Ocean sector of the Southern Ocean between February and April 2025 (~1,200 km of sampling).",
    station: "Southern Ocean",
    year: 2025,
    format: "NetCDF",
    size: "312 MB",
    records: "400+ profiles",
  },
  {
    id: "d007",
    title: "Ice-Tethered Mooring Data — Quilty Bay",
    category: "Oceans",
    description:
      "Underwater mooring data from Quilty Bay, Larsemann Hills, redeployed during the 44th ISEA, capturing oceanographic and cryosphere parameters year-round.",
    station: "Quilty Bay, Larsemann Hills",
    year: 2025,
    format: "NetCDF",
    size: "210 MB",
    records: "2 deployments",
  },
  {
    id: "d008",
    title: "Nivl Ice Shelf Radar Survey (SENS)",
    category: "Cryosphere",
    description:
      "Hovercraft-based ground-penetrating radar survey of the Nivl Ice Shelf conducted under the SENS campaign — 400+ km of transects mapping internal ice structure.",
    station: "Nivl Ice Shelf, East Antarctica",
    year: 2025,
    format: "GeoTIFF / ASCII",
    size: "1.4 GB",
    records: "400+ km transects",
  },
  {
    id: "d009",
    title: "Polar Ice Core Paleoclimatic Reconstruction",
    category: "Paleoclimate",
    description:
      "High-resolution δ18O and accumulation records from ice cores providing multi-millennial climate reconstruction for East Antarctica.",
    station: "East Antarctica",
    year: 2024,
    format: "Excel / CSV",
    size: "54 MB",
    records: "40,000 data points",
  },
  {
    id: "d010",
    title: "Southern Ocean Hydrography (CTD/XBT)",
    category: "Oceans",
    description:
      "Conductivity–temperature–depth and expendable bathythermograph casts along Indian Ocean-sector transects collected during Indian Southern Ocean expeditions since 2004.",
    station: "Southern Ocean",
    year: 2024,
    format: "NetCDF",
    size: "2.1 GB",
    records: "5 transects",
  },
  {
    id: "d011",
    title: "Sea Ice Concentration & Extent (Satellite)",
    category: "Cryosphere",
    description:
      "Satellite-derived sea-ice concentration and extent in the Indian Ocean sector of the Southern Ocean and the Arctic, from passive-microwave and SAR sensors.",
    station: "Polar seas",
    year: 2026,
    format: "NetCDF / GeoTIFF",
    size: "2.4 GB",
    records: "Daily grids",
  },
  {
    id: "d012",
    title: "Synoptic Surface Data (Antarctic Stations)",
    category: "Atmosphere",
    description:
      "Synoptic meteorological observations and surface pressure/temperature series from Indian Antarctic stations served through the NPDC surface-station data interface.",
    station: "Maitri & Bharati",
    year: 2026,
    format: "CSV",
    size: "120 MB",
    records: "Live + archive",
  },
];

export const publications: Publication[] = [
  {
    id: "p001",
    title: "Modern-like deep-water circulation in the Indian Ocean caused by the Central American Seaway closure",
    authors: "Prabhat, P., Rahaman, W., Lathika, N., Tarique, M., Mishra, R., Thamban, M.",
    journal: "Nature Communications",
    year: 2022,
    doi: "10.1038/s41467-022-35145-0",
    type: "Research Paper",
  },
  {
    id: "p002",
    title: "Weakening of the South Asian summer monsoon linked to interhemispheric ice-sheet growth since 12 Ma",
    authors: "Yao, Z., Shi, X., Guo, Z., Li, X., Nath, B. N., Betzler, C., Zhang, H., Lindhorst, S., Miriyala, P.",
    journal: "Nature Communications",
    year: 2023,
    doi: "10.1038/s41467-023-36537-6",
    type: "Research Paper",
  },
  {
    id: "p003",
    title: "The lower oceanic crust at ultraslow-spreading Southwest Indian Ridge: the inside story",
    authors: "Dhar, A., Ghosh, B., Bandyopadhyay, D., Morishita, T., et al.",
    journal: "Gondwana Research",
    year: 2022,
    doi: "10.1016/j.gr.2022.08.008",
    type: "Research Paper",
  },
  {
    id: "p004",
    title: "Palaeoceanographic significance of aragonitic pteropods in the Indian Ocean – a review",
    authors: "Sreevidya, E., Sijinkumar, A. V., Nath, B. N.",
    journal: "Boreas",
    year: 2022,
    doi: "10.1111/bor.12540",
    type: "Research Paper",
  },
  {
    id: "p005",
    title: "Stable δ13C and δ15N isotope and palynofacies study of the late Miocene to early Pliocene Nicobar Fan sediments, Indian Ocean",
    authors: "Biswas, S., Pandey, D. K., Nair, N., et al.",
    journal: "Geo-Marine Letters",
    year: 2023,
    doi: "10.1007/s00367-023-00755-0",
    type: "Research Paper",
  },
  {
    id: "p006",
    title: "Latitudinal variance in the drivers and pacing of warmth during Mid-Pleistocene MIS 31 in the Antarctic zone of the Southern Ocean",
    authors: "Tauxe, L., Tripathi, S., Zheng, X., Stoner, J. R., Scherer, R. P.",
    journal: "Paleoceanography and Paleoclimatology",
    year: 2022,
    doi: "10.1029/2021PA004394",
    type: "Research Paper",
  },
  {
    id: "p007",
    title: "Benthic foraminiferal survival through the early Paleocene (Danian) greenhouse climate interval, IODP Site U1457 (Laxmi Basin, Northern Indian Ocean)",
    authors: "NCPOR Paleo Group",
    journal: "Evolving Earth",
    year: 2023,
    doi: "10.1x/EVOE-1-100003",
    type: "Research Paper",
  },
  {
    id: "p008",
    title: "Hydrographic section along 55°E in the Indian and Southern oceans",
    authors: "Katsumata, K., Aoki, S., Ohshima, K. I., Yamamoto-Kawai, M.",
    journal: "Ocean Science",
    year: 2025,
    doi: "10.5194/os-21-419-2025",
    type: "Research Paper",
  },
];

export const mediaItems: MediaItem[] = [
  {
    id: "m001",
    type: "photo",
    title: "Maitri station in the Schirmacher Oasis",
    src: "https://upload.wikimedia.org/wikipedia/commons/4/46/An_ariel_view_of_the_Indian_Station_Maitri%2C_Antarctica_on_February_2%2C2005.jpg",
    expedition: "45th ISEA",
    year: 2025,
    location: "Maitri, Antarctica",
    tags: ["station", "landscape"],
  },
  {
    id: "m002",
    type: "photo",
    title: "Adelie penguin colony, Rosenthal Island",
    src: "https://upload.wikimedia.org/wikipedia/commons/9/90/Colony_of_Adelie_Penguin_at_Cape_Royds.jpg",
    expedition: "44th ISEA",
    year: 2024,
    location: "Princess Astrid Coast, Antarctica",
    tags: ["wildlife", "penguin"],
  },
  {
    id: "m003",
    type: "photo",
    title: "Bharati station, Larsemann Hills",
    src: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Bharati_permanent_Antarctic_research_station.jpg",
    expedition: "44th ISEA",
    year: 2024,
    location: "Bharati, Antarctica",
    tags: ["winterover", "station"],
  },
  {
    id: "m004",
    type: "photo",
    title: "Ny-Ålesund, the world's northernmost settlement",
    src: "https://upload.wikimedia.org/wikipedia/commons/c/ca/2015-07-31_Ny_Alesund%2C_Svalbard%2C_Arctic.jpg",
    expedition: "16th IArE",
    year: 2025,
    location: "Ny-Ålesund, Svalbard",
    tags: ["arctic", "station"],
  },
  {
    id: "m005",
    type: "photo",
    title: "Polar ice-core drilling rig",
    src: "https://upload.wikimedia.org/wikipedia/commons/1/1c/Ice-core_drill_hg.jpg",
    expedition: "41st ISEA",
    year: 2021,
    location: "Schirmacher Oasis",
    tags: ["cryosphere", "fieldwork"],
  },
  {
    id: "m006",
    type: "video",
    title: "Deploying the ocean glider into the Southern Ocean",
    src: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Antarctica_WAIS_Divide_Field_Camp_10.jpg",
    expedition: "44th ISEA",
    year: 2025,
    location: "Southern Ocean",
    tags: ["voyage", "ocean"],
    duration: "6:10",
  },
  {
    id: "m007",
    type: "photo",
    title: "Aurora australis over the polar night",
    src: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Aurora_Australis_From_ISS.JPG",
    expedition: "44th ISEA",
    year: 2024,
    location: "Antarctica",
    tags: ["aurora", "landscape"],
  },
  {
    id: "m008",
    type: "video",
    title: "Research vessel en route through heavy seas",
    src: "https://upload.wikimedia.org/wikipedia/commons/4/40/Aurora_australis_dancing_over_an_LED_illuminated_igloo.jpg",
    expedition: "45th ISEA",
    year: 2025,
    location: "Southern Ocean",
    tags: ["voyage", "logistics"],
    duration: "1:55",
  },
  {
    id: "m009",
    type: "photo",
    title: "Polar meteorologist releasing a radiosonde weather balloon",
    src: "https://upload.wikimedia.org/wikipedia/commons/1/10/Aurora_Australis_%28icebreaker%29_berthed_in_Hobart_under_a_rainbow.jpg",
    expedition: "45th ISEA",
    year: 2025,
    location: "Maitri, Antarctica",
    tags: ["meteorology", "fieldwork"],
  },
  {
    id: "m010",
    type: "photo",
    title: "ORV Sagar Manthan under construction at GRSE, Kolkata",
    src: "https://upload.wikimedia.org/wikipedia/commons/e/ef/NOR-2016-Svalbard-Ny-%C3%85lesund-Blue_house_02_%28with_bust_of_Amundsen%29.jpg",
    expedition: "—",
    year: 2026,
    location: "Kolkata, India",
    tags: ["vessel", "institutional"],
  },
];

export const activities: Activity[] = [
  {
    id: "a001",
    title: "Launch of ORV Sagar Manthan for NCPOR",
    date: "2026-09-09",
    category: "Institutional",
    summary:
      "India's first advanced indigenous Ocean Research Vessel, ORV Sagar Manthan, was launched at Rishi Bankim Shipyard, Kolkata by GRSE for NCPOR.",
    content:
      "The 89.5 m, ₹840-crore vessel, built by Garden Reach Shipbuilders & Engineers (GRSE) for NCPOR, will replace the 43-year-old ORV Sagar Kanya. It is designed for severe sea states and research in the Southern Ocean, with dynamic positioning, multibeam and seismic survey capability, AUV/ROV handling and a projected service life of 30 years. Launch at Kolkata on 9 September 2026.",
  },
  {
    id: "a002",
    title: "New Ocean Research Vessel: first steel cutting under Deep Ocean Mission",
    date: "2024-11-29",
    category: "Institutional",
    summary:
      "The ceremonial first cutting of steel for the new 89.5 m multidisciplinary ORV took place at GRSE, Kolkata, under the Deep Ocean Mission.",
    content:
      "Chief Guest Dr. M. Ravichandran, Secretary MoES, performed the first steel-cutting at GRSE Kolkata on 29 November 2024. The vessel is expected to be commissioned in December 2027 for the ocean science fraternity.",
  },
  {
    id: "a003",
    title: "NCPOR signs MoA for India's first Polar and Ocean Museum",
    date: "2026-03-01",
    category: "Institutional",
    summary:
      "NCPOR signed a Memorandum of Agreement for the development of India's first dedicated Polar and Ocean Museum at NCPOR, Goa.",
    content:
      "The MoA paves the way for a public-facing museum dedicated to India's polar and ocean research, showcasing expeditions, stations, vessels and cryosphere science.",
  },
  {
    id: "a004",
    title: "Strengthening Indo-Norwegian Arctic Research Collaboration",
    date: "2026-02-20",
    category: "Collaboration",
    summary:
      "India and Norway renewed their collaboration on Arctic research spanning atmospheric science, glaciology and marine biology in Svalbard.",
    content:
      "The renewed cooperation strengthens like-minded partnerships between Himadri (Ny-Ålesund) and Norwegian Arctic platforms, enabling shared logistics and data interoperability.",
  },
  {
    id: "a005",
    title: "45th Indian Scientific Expedition to Antarctica sets sail",
    date: "2025-10-31",
    category: "Expedition",
    summary:
      "The first team of the 45th ISEA departed Mumbai on 31 October 2025, reaching Maitri on 4 November 2025.",
    content:
      "The 45th expedition continues India's uninterrupted Antarctic presence, with winter-over relief, resupply and long-term atmospheric, glaciological and life-science observations at Maitri and Bharati.",
  },
  {
    id: "a006",
    title: "Call for Proposals: Indian Antarctic Expedition 2026–27",
    date: "2026-06-01",
    category: "Call for Proposals",
    summary:
      "NCPOR invites proposals from Indian institutions for participation in the forthcoming Indian Scientific Expedition to Antarctica (2026–27).",
    content:
      "Researchers across atmospheric sciences, cryosphere, Earth sciences, oceanography and biology are invited to propose experiments for the Antarctic season through NCPOR's online expedition portal.",
  },
  {
    id: "a007",
    title: "International Yoga Day celebrations at NCPOR",
    date: "2026-06-21",
    category: "Outreach",
    summary:
      "NCPOR marked International Yoga Day 2026, part of a series of wellness and outreach activities at the Goa campus.",
    content:
      "The event reflects the institute's year-round wellness, outreach and capacity-building programme alongside its polar and ocean research commitments.",
  },
];

export const stationWeather: StationWeather[] = [
  { station: "Maitri", region: "Antarctica", temp: -16.8, wind: 21, pressure: 988, humidity: 78, icon: "❄️" },
  { station: "Bharati", region: "Antarctica", temp: -21.4, wind: 34, pressure: 976, humidity: 82, icon: "❄️" },
  { station: "Himansh", region: "Himalaya", temp: 7.4, wind: 12, pressure: 1012, humidity: 41, icon: "🌤️" },
  { station: "Himadri", region: "Arctic", temp: 5.5, wind: 18, pressure: 1003, humidity: 89, icon: "🌧️" },
];

export const regions: Region[] = ["Antarctica", "Arctic", "Southern Ocean", "Himalaya"];

export const stats = {
  expeditions: "45+",
  datasets: "850+",
  publications: "2,400",
  stations: "4",
  yearsOfPolarPresence: "45+",
  mediaAssets: "12,500",
};

export function getExpedition(slug: string) {
  return expeditions.find((e) => e.slug === slug);
}

export function getDatasetCategories() {
  return [...datasetCategories];
}

export function getRegionColor(region: Region) {
  switch (region) {
    case "Antarctica":
      return "bg-sky-100 text-sky-700";
    case "Arctic":
      return "bg-cyan-100 text-cyan-700";
    case "Southern Ocean":
      return "bg-blue-100 text-blue-700";
    case "Himalaya":
      return "bg-slate-200 text-slate-700";
  }
}

export const vessels: Vessel[] = [
  {
    id: "orv-sagar-manthan",
    name: "ORV Sagar Manthan",
    type: "Ocean Research Vessel (New Build)",
    operator: "ESSO — NCPOR",
    status: "In Harbour",
    ocean: "Hooghly River",
    destination: "Kolkata (post-launch fitting)",
    lat: 22.0,
    lng: 88.3,
    heading: 0,
    speed: 0,
    distanceCovered: 0,
    daysAtSea: 0,
    startDate: "—",
    crew: 80,
    icon: "🚢",
    route: [],
  },
  {
    id: "orv-sagar-kanya",
    name: "ORV Sagar Kanya",
    type: "Oceanographic Research Vessel",
    operator: "ESSO — NCPOR",
    status: "In Harbour",
    ocean: "Arabian Sea",
    destination: "Port Goa",
    lat: 15.4,
    lng: 73.8,
    heading: 0,
    speed: 0,
    distanceCovered: 0,
    daysAtSea: 0,
    startDate: "—",
    crew: 58,
    icon: "⚓",
    route: [],
  },
  {
    id: "orv-sagar-nidhi",
    name: "ORV Sagar Nidhi",
    type: "Ice-strengthened Research Vessel",
    operator: "NIOT (MoES fleet)",
    status: "Resupply Mission",
    ocean: "Southern Ocean",
    destination: "Maitri Station (Schirmacher Oasis)",
    lat: -56.8,
    lng: 11.0,
    heading: 142,
    speed: 11,
    distanceCovered: 3680,
    daysAtSea: 15,
    startDate: "2025-11-20",
    crew: 62,
    icon: "🛳️",
    route: [
      { lat: -18.0, lng: 55.0 },
      { lat: -35.0, lng: 35.0 },
      { lat: -50.0, lng: 18.0 },
      { lat: -56.8, lng: 11.0 },
      { lat: -63.0, lng: 11.6 },
    ],
  },
  {
    id: "ins-saryu",
    name: "INS Saryu",
    type: "Naval Offshore Patrol Vessel",
    operator: "Indian Navy",
    status: "At Sea",
    ocean: "Southern Ocean",
    destination: "Bharati Station (Larsemann Hills)",
    lat: -58.2,
    lng: 28.5,
    heading: 158,
    speed: 14,
    distanceCovered: 4120,
    daysAtSea: 19,
    startDate: "2025-11-05",
    crew: 120,
    icon: "🚢",
    route: [
      { lat: -15.0, lng: 73.8 },
      { lat: -30.0, lng: 60.0 },
      { lat: -45.0, lng: 40.0 },
      { lat: -58.2, lng: 28.5 },
      { lat: -66.5, lng: 29.0 },
    ],
  },
];